### PR TITLE
Added tutorial OF-OF case

### PR DESCRIPTION
**Pull request by arpans16**
Changes made:

1. Tutorial case added - for now, it is only a one-way coupling, after this has been rigorously tested I will push the two-way coupling case
2. Additional variables added to the FF module which is the module used in the tutorial case
3. Interface.C has been updated to include face centers at internal cell faces (volSurf)

### CODE REVIEW

**Comment by arpans16** [comment]
Hi @Alphaoo1  - I added the tutorial case in your branch, please review it when you find time

**Comment by prasadadhav** [comment]
@arpans16 Thank you very much for the Case.
The [description](https://github.com/arpans16/openfoam-adapter/tree/master/tutorial/volCoup-oneWay) for the test case is much more thorough than what currently have.

Over some email conversations with @Makish and @Davidscn, we have thought of making a `Volume_Coupling` module. This module will contain all the data fields related to volume coupling in there in the initial phase, so as to differentiate between surface data fields and volume data fields, the easiest example is Velocity.

My initial remarks would be to divide this PR into smaller manageable chunks.
- One PR for Volume surface coupling.
- Second PR for data fields (I will be making a `Volume_Coupling` module, maybe it would be a good idea to put the data fields there but until my changes are accepted they are ok in `FF`).
- And a third PR for the test cases.

This will make it easy to track the changes.
The implementation you have seems a bit different than mine, but I am not entirely sure. In any case, with separate PR it might be easier to test both implementations if they are indeed different.

I would also like to [mention](https://github.com/precice/openfoam-adapter/pull/182#issuecomment-851552838) that @MakisH has created a [branch](https://github.com/precice/openfoam-adapter/tree/volume-coupling) for developing the `volume_coupling`, so it might be a good idea to open a PR based on that branch. We will also get more eyes on the work from the team.

**Comment by arpans16** [comment]
Hi @Alphaoo1  - I had a couple of questions for you offline, could you send me your email id, or email me at sircara@ornl.gov
I wanted to know about how to create these multiple PRs (basic questions since I am a GitHub noob)

**Comment by arpans16** [comment]
Closing this PR to open one with only changes in Interface.C

**Pull request closed without merging**
